"""
Django settings for Tadbir3 project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
import os
from datetime import timedelta

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'uyo!60rb9ri4c8_vb4*e7z9*u3n5!$$#^0znnf4lj8t4h02-0i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'Fira_app',
    'rest_framework',
    'corsheaders',
    'ckeditor',
    'ckeditor_uploader',
    'django_wysiwyg',
    'request',
    'taggit',
    'sorl.thumbnail',
    'rest_framework_simplejwt',
    'task.apps.TaskConfig',
    'tasklog',
    'user',
    'knowledge',
    'performance',
    'resource',
]

DJANGO_WYSIWYG_FLAVOR="ckeditor"

CKEDITOR_UPLOAD_PATH="ckeditor/uploads/"



CKEDITOR_FILENAME_GENERATOR = 'Fira.utils.get_filename'

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3030',  # Update with your frontend URL
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_CREDENTIALS = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'request.middleware.RequestMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Fira.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Fira.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': 'mydatabase', # This is where you put the name of the db file. 
#                  # If one doesn't exist, it will be created at migration time.
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'fira_db',
        'USER':'postgres',
        'PASSWORD':'',
        'HOST':'localhost',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'fa'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT="static/"


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')


CKEDITOR_CONFIGS = {
    'default':{
        'toolbar':'Custom',
        'toolbar_Custom':[
            ["Paste","PasteText","PasteFromWord","Find","Replace" ],
            ["Image", "Flash", "Table", "HorizontalRule","TextColor", "BGColor","Smiley", "SpecialChar","NumberedList", "BulletedList", "Undo", "Redo","Link", "Unlink"],
            ["Styles", "Format", "-", "Bold",  "Italic", "Underline", "Strike", "Subscript", "SuperScript","JustifyLeft","JustifyCenter","JustifyRight","JustifyBlock","BidiLtr","BidiRtl"],
        ],
        "width": "100%",
        "height": "100%",
        "filebrowserWindowWidth": 500,
        "filebrowserWindowHeight": 725,
        
    }
}
# 'uiColor':"#786aff"

CKEDITOR_ALLOW_NONIMAGE_FILES=False

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES':[
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME':timedelta(minutes=45),
    'REFRESH_TOKEN_LIFETIME':timedelta(days=30),
}

# Allow only 'http://localhost:3030' as the origin
CORS_ORIGIN_WHITELIST = [
'http://localhost:3030',
'http://127.0.0.1:3030',
'http://kara2.medad-art.ir'
]

