# Generated by Django 3.0.7 on 2024-05-09 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tadbir3_app', '0239_auto_20240509_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskExtend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_deadline', models.DateField()),
                ('requested_deadline', models.DateField()),
                ('description', models.TextField()),
                ('rejected', models.BooleanField(default=False)),
                ('accepted_deadline', models.DateField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extends', to='Tadbir3_app.Task')),
            ],
            options={
                'db_table': 'task_extend',
            },
        ),
    ]
